apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  generateName: robocode-example-manual-
  namespace: mlflow
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      containers:
      - command:
        - python
        - pipeline.py
        - --timesteps
        - "100000"
        - --record-timesteps
        - "2000"
        - --policy
        - "CnnPolicy"
        - --load-model
        - "/artifacts/models/789a56dc29a049f98ef2cd080262b201/robocode-model"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: aws-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: aws-key
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.10.20.50.162.nip.io:8080
        - name: MLFLOW_EXPERIMENT_ID
          value: "1"
        image: gcr.io/stobias-dev/robocode-mlflow-run
        imagePullPolicy: Always
        name: robocode-example
        volumeMounts:
          - mountPath: /artifacts/
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: experiments
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 100