apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  generateName: robocode-example-2-
  namespace: mlflow
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - python
        - pipeline.py
        - --timesteps
        - "50000"
        - --record-timesteps
        - "2000"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: aws-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: aws-key
        image: gcr.io/stobias-dev/robocode-mlflow-example:6615db3
        imagePullPolicy: Always
        name: robocode-example-2
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 100

