---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlfllow-vol2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath