apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  template:
    metadata:
      name: mlflow
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: gcr.io/stobias-dev/mlflow:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          command:
            - mlflow
            - server
            - -h
            - 0.0.0.0
            - --backend-store-uri
            - sqlite:///data/mlflow.db
            - --serve-artifacts
            - --artifacts-destination
            - s3://mlflow-s3-bucket
            - --gunicorn-opts
            -  "--access-logfile '-' --error-logfile '-'"
          volumeMounts:
          - mountPath: /data
            name: mlfllow-vol2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-key
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-key
                key: aws_secret_access_key
      restartPolicy: Always
      volumes:
      - name: mlfllow-vol2
        persistentVolumeClaim:
          claimName: mlfllow-vol2
  selector:
    matchLabels:
      app: mlflow
