apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
